### ISSUE TITLE
NN has a mistake

### ISSUE THREAD

**Issue by dogegg250** [jeongyoonlee/Kaggler#14]
# dl/dz = dl/dy * dy/dz = dl/dy * w1
dl_dz = dl_dy * self.w1[j]

I think it's
dl_dz = dl_dy * self.w1[j] * (0 or 1)

am I  right?

**Comment by jeongyoonlee** [comment]
`z[j]` is always 1.
see line 201-203:
```
            # update weights related to non-zero hidden units
            if self.z[j] == 0.:
                continue
```

**Comment by dogegg250** [comment]
it seems you are right
