### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by ahbon123** [jeongyoonlee/Kaggler#36]
Hello, 

I try to install kaggler with pip under Mac OS: `pip install -U Kaggler`, but I get the errors below. 

Could anyone help me to fix it? Thanks. 

`Building wheels for collected packages: Kaggler
  Building wheel for Kaggler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"'; __file__='"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-wheel-ah9hp8b7 --python-tag cp37
       cwd: /private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/
  Complete output (43 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler
  copying kaggler/data_io.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
  copying kaggler/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
  copying kaggler/const.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
  copying kaggler/feature_selection/feature_selection.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
  copying kaggler/feature_selection/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
  copying kaggler/ensemble/linear.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
  copying kaggler/ensemble/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/model
  copying kaggler/model/nn.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
  copying kaggler/model/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
  copying kaggler/model/automl.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
  copying kaggler/metrics/regression.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
  copying kaggler/metrics/classification.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
  copying kaggler/metrics/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
  copying kaggler/online_model/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
  copying kaggler/online_model/classification_tree.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
  creating build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
  copying kaggler/preprocessing/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
  copying kaggler/preprocessing/data.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
  running build_ext
  skipping 'kaggler/online_model/ftrl.c' Cython extension (up-to-date)
  building 'kaggler.online_model.ftrl' extension
  creating build/temp.macosx-10.14-x86_64-3.7
  creating build/temp.macosx-10.14-x86_64-3.7/kaggler
  creating build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model
  creating build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model/murmurhash
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/lib/python3.7/site-packages/numpy/core/include -c kaggler/online_model/ftrl.c -o build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model/ftrl.o -O3 -mmacosx-version-min=10.9
  In file included from kaggler/online_model/ftrl.c:4:
  /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for Kaggler
  Running setup.py clean for Kaggler
Failed to build Kaggler
Installing collected packages: Kaggler
  Running setup.py install for Kaggler ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"'; __file__='"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-record-qohfjlru/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/
    Complete output (43 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler
    copying kaggler/data_io.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
    copying kaggler/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
    copying kaggler/const.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
    copying kaggler/feature_selection/feature_selection.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
    copying kaggler/feature_selection/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/feature_selection
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
    copying kaggler/ensemble/linear.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
    copying kaggler/ensemble/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/ensemble
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/model
    copying kaggler/model/nn.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
    copying kaggler/model/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
    copying kaggler/model/automl.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/model
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
    copying kaggler/metrics/regression.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
    copying kaggler/metrics/classification.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
    copying kaggler/metrics/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/metrics
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
    copying kaggler/online_model/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
    copying kaggler/online_model/classification_tree.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/online_model
    creating build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
    copying kaggler/preprocessing/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
    copying kaggler/preprocessing/data.py -> build/lib.macosx-10.14-x86_64-3.7/kaggler/preprocessing
    running build_ext
    skipping 'kaggler/online_model/ftrl.c' Cython extension (up-to-date)
    building 'kaggler.online_model.ftrl' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    creating build/temp.macosx-10.14-x86_64-3.7/kaggler
    creating build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model
    creating build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model/murmurhash
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/lib/python3.7/site-packages/numpy/core/include -c kaggler/online_model/ftrl.c -o build/temp.macosx-10.14-x86_64-3.7/kaggler/online_model/ftrl.o -O3 -mmacosx-version-min=10.9
    In file included from kaggler/online_model/ftrl.c:4:
    /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"'; __file__='"'"'/private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-install-f8todfi2/Kaggler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_g/2rrxbrnj1xb_h5k70xgtdss00000gn/T/pip-record-qohfjlru/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by jeongyoonlee** [comment]
This might be resolved by upgrading X-code command line. Could you upgrade X-code command line tool to 10.x and see if it resolve the issue?
