### ISSUE TITLE
Set embedding layer to n_uniq + 1

### ISSUE THREAD

**Issue by ppstacy** [jeongyoonlee/Kaggler#43]
Hi @jeongyoonlee, I am getting following error when using EmbeddingEncoder()

`InvalidArgumentError: indices[389,0] = 3 is not in [0, 3)
[[{{node prior_rider_segment_emb/embedding_lookup}}]]`

I might be wrong but I think this happened because index starting from 0. Could we set the embedding layer to n_uniq +1 that will handle the out of bound index error.

**Comment by jeongyoonlee** [comment]
It is supposed to be `n_uniq`, which is the number of unique values. Could you share more code and info on the column that causes the error?

**Comment by ppstacy** [comment]
I think this happened because of this column 'prior_rider_segment' column including missing values, for example:
`array([nan, 'a rider', 'b rider', 'c rider'], dtype=object)`

`X[col].nunique()` with default setting `dropna=True` will just return 3. It might be an edge case happened when we have missing values larger than the `min_obs` number and label encoding will recognize as a category.

**Comment by jeongyoonlee** [comment]
It label-encodes a categorical feature first and `nan` should be taken care of already. Could you share code and data that reproduce the issue?

**Comment by ppstacy** [comment]
Thanks @jeongyoonlee ! Please correct me if I am wrong, I think we are calling `nunique()` in `def _get_model()` which is before the label-coding in `fit()`. I followed the test file and used the following code: 

`RANDOM_SEED = 42`
`N_FOLD = 5`
`threshold = int(0.01 * df.shape[0])`
`cv = StratifiedKFold(n_splits=N_FOLD, shuffle=True, random_state=RANDOM_SEED)`
`ee = EmbeddingEncoder(cat_cols=CAT_COLS,
                      num_cols=INT_COLS,
                      cv=cv,
                      random_state=RANDOM_SEED, min_obs=threshold, batch_size=10*threshold)`
`X_emb = ee.fit_transform(X=X_train, y=y_train)`

**Comment by eyadsibai** [comment]
There is a rule of thumb that was shared in the fastai course (if I am not mistaken)

**Comment by jeongyoonlee** [comment]
> Thanks @jeongyoonlee ! Please correct me if I am wrong, I think we are calling `nunique()` in `def _get_model()` which is before the label-coding in `fit()`. I followed the test file and used the following code:
> 
> `RANDOM_SEED = 42`
> `N_FOLD = 5`
> `threshold = int(0.01 * df.shape[0])`
> `cv = StratifiedKFold(n_splits=N_FOLD, shuffle=True, random_state=RANDOM_SEED)`
> `ee = EmbeddingEncoder(cat_cols=CAT_COLS, num_cols=INT_COLS, cv=cv, random_state=RANDOM_SEED, min_obs=threshold, batch_size=10*threshold)`
> `X_emb = ee.fit_transform(X=X_train, y=y_train)`

Label encoding is called before training the embedding layers. See https://github.com/jeongyoonlee/Kaggler/blob/8819770f3a1c86b2f2987740bb74999717ebf788/kaggler/preprocessing/categorical.py#L451

**Comment by jeongyoonlee** [comment]
> Thanks @jeongyoonlee ! Please correct me if I am wrong, I think we are calling `nunique()` in `def _get_model()` which is before the label-coding in `fit()`. I followed the test file and used the following code:
> 
> `RANDOM_SEED = 42`
> `N_FOLD = 5`
> `threshold = int(0.01 * df.shape[0])`
> `cv = StratifiedKFold(n_splits=N_FOLD, shuffle=True, random_state=RANDOM_SEED)`
> `ee = EmbeddingEncoder(cat_cols=CAT_COLS, num_cols=INT_COLS, cv=cv, random_state=RANDOM_SEED, min_obs=threshold, batch_size=10*threshold)`
> `X_emb = ee.fit_transform(X=X_train, y=y_train)`

Oh right. Label encoding is actually called before `_get_model()`, but I used `X[col]` instead of `X_cat[col]` to get `n_uniq`.

Will update it soon.

Thanks for catching this.

**Comment by ppstacy** [comment]
Right, Label encoding called before `_get_model()`. Thanks for fixing it!
